let nodes = {
    paths: [
      "complementar/dicionário",
      "complementar/método-de-estudo",
      "diário-de-aulas/04-09-23",
      "diário-de-aulas/06-09-23",
      "diário-de-aulas/14-09-23",
      "diário-de-aulas/18-09-23",
      "diário-de-aulas/25-09-23",
      "diário-de-aulas/30-08-23",
      "diário-de-aulas/31-08-23",
      "matérias/direito-civil-i/direitos-da-personalidade",
      "matérias/filosofia-jurídica/trabalhos/1ª-atividade-avaliativa-textos",
      "matérias/filosofia-jurídica/filosofia",
      "matérias/filosofia-jurídica/filosofia-contemporâneo",
      "matérias/filosofia-jurídica/filosofia-moral",
      "matérias/introdução-ao-estudo-do-direito/axiologia-jurídica",
      "matérias/introdução-ao-estudo-do-direito/hermenêutica-jurídica",
      "matérias/introdução-ao-estudo-do-direito/introdução-ao-estudo-do-direito",
      "matérias/introdução-ao-estudo-do-direito/norma-jurídica",
      "trabalhos/apresentação-ied",
      "trabalhos/direito-civil",
      "datas-importantes",
      "index",
    ],
    nodeCount: 22,
    linkSources: [3, 4, 6, 8, 8, 11],
    linkTargets: [11, 14, 9, 16, 19, 3],
    labels: [
      "Dicionário",
      "Método de estudo",
      "04-09-23",
      "06-09-23",
      "14-09-23",
      "18-09-23",
      "25-09-23",
      "30-08-23",
      "31-08-23",
      "Direitos da Personalidade",
      "1ª Atividade Avaliativa - Textos",
      "Filosofia",
      "Filosofia Contemporâneo",
      "Filosofia Moral",
      "Axiologia Jurídica",
      "Hermenêutica Jurídica",
      "Introdução ao Estudo do Direito",
      "Norma Jurídica",
      "Apresentação IED",
      "Direito Civil",
      "Datas importantes",
      "Index",
    ],
    radii: [
      3, 3, 3, 7, 6.4375, 3, 6.4375, 3, 7, 6.4375, 3, 7, 3, 3, 6.4375, 3,
      6.4375, 3, 3, 6.4375, 3, 3,
    ],
    linkCount: 6,
  },
  attractionForce = 1,
  linkLength = 10,
  repulsionForce = 150,
  centralForce = 3,
  edgePruning = 100;
